/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import IndicateCard from "./Script/IndicateCard"
import GameControl from "./Script/GameControl"
import LevelsNode from "./Script/LevelsNode"
import DigitalCard from "./Script/DigitalCard"
import GameOver from "./Script/GameOver"
import Ranking from "./Script/Ranking"
import StartGame from "./Script/StartGame"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Script/IndicateCard.ts",IndicateCard);
        reg("Script/GameControl.ts",GameControl);
        reg("Script/LevelsNode.ts",LevelsNode);
        reg("Script/DigitalCard.ts",DigitalCard);
        reg("Script/GameOver.ts",GameOver);
        reg("Script/Ranking.ts",Ranking);
        reg("Script/StartGame.ts",StartGame);
    }
}
GameConfig.init();